# bert.yaml
program: scripts/train_bert.py
name: "ASGARD"
project: "ASGARD"
method: random
metric:
  name: Hamming Score
  goal: maximize
parameters:
  model_architecture:
    values: ["bert"]
  class_weight_kind:
    values: ["balanced", "two-to-one", "None"]
    probabilities: [0.1, 0.6, 0.3]
  dropout:
    values: [0.1, 0.15, 0.2]
  epochs:
    values: [4, 5, 6]
  learning_rate:
    values: [1e-5, 3e-5, 6e-5, 1e-4, 2.5e-4]
command:
  - python
  - scripts/train_bert.py
  - ${args}