# rnn.yaml
name: "ASGARD-RNN"
method: bayes
metric:
  name: accuracy
  goal: maximize
parameters:
  learning_rate:
    values: [1e-3, 2e-3, 3e-3, 4e-3, 5e-3]
  rate:
    values: [1, 1.5, 2, 2.5]
  weight_constraint:
    values: [None, 1., 3., 5.]
  optimizer:
    values: ["adam", "RMSprop", "nadam"]
  dropout:
    values: [0.2, 0.3, 0.4]
  units:
    values: [20, 30, 40, 50, 60]
  epochs:
    values: [6, 8, 10]
  output_sequence_length:
    values: [20, 30, 40]
  class_weight_kind:
    values: ["balanced", "two-to-one", None]
  n_hidden:
    values: [1, 2, 3]