name: asgard

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up asgard project
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.13"
      - name: Install dependencies
        run: |
          make install-dependencies
      - name: Install packages
          make requirements
          make requirements-lint
      - name: Linting checks
        run:
          make checks